name: Test

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "Paste YouTube URL"
        required: true
        type: string

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        run: |
          pip install youtube-transcript-api

      - name: Extract transcript
        run: |
          python main.py "${{ inputs.youtube_url }}"
